export const localKeys = {
  temperature: "temperature",
  feelsLikeTemperature: "feels-like-temperature",
  city: "city",
  name: "name",
  icon: "icon",
  windDirection: "wind-direction",
  windSpeed: "wind-speed",
  recentRain: "recent-rain",
  humidity: "humidity",
  imageDateForDay: "image-date-for-day",
  searchEngine: "search-engine",
  weatherMetric: "weather-metric",
  currentBgImage: "current-bg-image",
  nextUpdate: "next-update",
  latitude: "latitude",
  longitude: "longitude",
  country: "country",
} as const;
